import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [

  {
    path: "dashboard",
    title: "Dashboard",
    icon: "../../../../assets/img/sidebar-bg/icons/dashboard.svg",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
  },
  {
    path: "profile",
    title: "My Profile",
    icon: "../../../../assets/img/sidebar-bg/icons/user - filled.svg",
        class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
  },
  {
    path: "resume",
    title: "My Resume",
    icon: "../../../../assets/img/sidebar-bg/icons/file - filled@2x.png",
        class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
  },
  {
    path: "meetings",
    title: "List of Meetings",
    icon: "../../../../assets/img/sidebar-bg/icons/group@2x.png",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
  },
  {
    path:"assessments",
    title:"List of Assesments",
    icon: "../../../../assets/img/sidebar-bg/icons/register@2x.png",
        class:"",
    badge:"",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
  },
  // {
  //   path:"changepassword",
  //   title:"Change Password",
  //   icon: "../../../../assets/img/sidebar-bg/icons/register@2x.png",
  //       class:"",
  //   badge:"",
  //   badgeClass: "",
  //   isExternalLink: false,
  //   submenu: [],
  // },
];
