import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [

  {
    path: "mydashboard",
    title: "Dashboard",
    icon: "../../../../assets/img/sidebarIcons/dashboard.svg",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
  },
  {
    path: 'user-managment/list-roles',
    title: "User Managment",
    icon: "../../../../assets/img/sidebarIcons/equalizer.svg",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
    // submenu: [
    //   {
    //     path: "add-user",
    //     title: "Add New User",
    //     icon: "ft-user-plus",
    //     class: "",
    //     badge: "",
    //     badgeClass: "",
    //     isExternalLink: false,
    //     submenu: [],
    //   },
    //   {
    //     path: "list-users",
    //     title: "List OF Users",
    //     icon: "ft-users",
    //     class: "",
    //     badge: "",
    //     badgeClass: "",
    //     isExternalLink: false,
    //     submenu: [],
    //   },
    //   {
    //     path: "add-profile",
    //     title: "Add New Profile",
    //     icon: "icon-user-follow",
    //     class: "",
    //     badge: "",
    //     badgeClass: "",
    //     isExternalLink: false,
    //     submenu: [],
    //   },
    //   {
    //     path: "list-profils",
    //     title: "List Of Profiles",
    //     icon: "fa fa-users",
    //     class: "",
    //     badge: "",
    //     badgeClass: "",
    //     isExternalLink: false,
    //     submenu: [],
    //   },
    //   {
    //     path: "add-role",
    //     title: "Add New Role",
    //     icon: "fa fa-plus",
    //     class: "",
    //     badge: "",
    //     badgeClass: "",
    //     isExternalLink: false,
    //     submenu: [],
    //   },
    //   {
    //     path: "list-roles",
    //     title: "List Of Roles",
    //     icon: "fa fa-list",
    //     class: "",
    //     badge: "",
    //     badgeClass: "",
    //     isExternalLink: false,
    //     submenu: [],
    //   }
    //   // ,
    //   // {
    //   //   path: "parameter",
    //   //   title: "Parameters",
    //   //   icon: "ft-trending-up",
    //   //   class: "",
    //   //   badge: "",
    //   //   badgeClass: "",
    //   //   isExternalLink: false,
    //   //   submenu: [],
    //   // },
    // ],
  },
  {
    path: "department",
    title: "Departments",
    icon: "../../../assets/img/sidebarIcons/pie-chart.svg",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
  },
  {
    path: "jobs/list",
    title: "Jobs",
    icon: "../../../assets/img/work.svg",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
  },
  {
    path: "screening",
    title: "Screening",
    icon: "../../../../assets/img/sidebarIcons/scan - fill.svg",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
  },
  {
    path: 'tasks',
    title: "Tasks",
    icon: "../../../../assets/img/sidebarIcons/calendar.svg",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
  },
  {
    path: "test-managment/testslist",
    title: "Test Management",
    icon: "../../../../assets/img/sidebarIcons/list.svg",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [
      // {
      //   path: "hrtest",
      //   title: "Create Tests",
      //   icon: "ft-edit",
      //   class: "",
      //   badge: "",
      //   badgeClass: "",
      //   isExternalLink: false,
      //   submenu: [],
      // },
      // {
      //   path: "technicaltest",
      //   title: "Technical Test",
      //   icon: "ft-edit",
      //   class: "",
      //   badge: "",
      //   badgeClass: "",
      //   isExternalLink: false,
      //   submenu: [],
      // },
      // {
      //   path: "firstcontact",
      //   title: "First Contact",
      //   icon: "ft-edit",
      //   class: "",
      //   badge: "",
      //   badgeClass: "",
      //   isExternalLink: false,
      //   submenu: [],
      // },
      // {
      //   path: "testslist",
      //   title: "List Of Tests",
      //   icon: "ft-list",
      //   class: "",
      //   badge: "",
      //   badgeClass: "",
      //   isExternalLink: false,
      //   submenu: [],
      // }
    ],
  },
  {
    path:"",
    title:"List of Meeting",
    icon: "../../../../assets/img/sidebarIcons/list.svg",
    class:"has-sub",
    badge:"2",
    badgeClass: "badge badge-pill badge-danger float-right mr-1 mt-1",
    isExternalLink: false,
    submenu: [
      {
        path: "withoutscreening",
        title: "Without Screening",
        icon: "ft-navigation",
        class: "",
        badge: "",
        badgeClass: "",
        isExternalLink: false,
        submenu: [],
      },
      // {
      //   path: "affectmeeting",
      //   title: "Affect Meeting",
      //   icon: "ft-clipboard",
      //   class: "",
      //   badge: "",
      //   badgeClass: "",
      //   isExternalLink: false,
      //   submenu: [],
      // },
      {
        path: "listofmeeting",
        title: "list OF Meeting",
        icon: "ft-list",
        class: "",
        badge: "",
        badgeClass: "",
        isExternalLink: false,
        submenu: [],
      },
      
    ],
  },{
    path: "assessments",
    title: "List of Assessments",
    icon: "../../../../assets/img/sidebarIcons/register.svg",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
  }
  ,
  // {
  //   path: "",
  //   title: "Environnements",
  //   icon: "ft-home",
  //   class: "has-sub",
  //   badge: "2",
  //   badgeClass: "badge badge-pill badge-danger float-right mr-1 mt-1",
  //   isExternalLink: false,
  //   submenu: [
  //     {
  //       path: "add-environment",
  //       title: "Ajouter environnement",
  //       icon: "",
  //       class: "",
  //       badge: "",
  //       badgeClass: "",
  //       isExternalLink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "list-environments",
  //       title: "Liste des environnements",
  //       icon: "",
  //       class: "",
  //       badge: "",
  //       badgeClass: "",
  //       isExternalLink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
 
];
